### ISSUE TITLE
测试其它数据集

### ISSUE THREAD

**Issue by lz-hust** [Audio-WestlakeU/FS-EEND#12]
老师您好！首先感谢您提供这样一个优质的项目！ 
我是一名刚刚涉足SD领域的本科生，正在尝试着在在您的项目上跑通其它数据集，我将数据集转换成您在issues11中提到的kaldi数据格式，也就是参考EEND中生成的mini_librispeech数据集格式：  
![image](https://github.com/user-attachments/assets/7a7580a7-222c-4ed1-86f9-d3fac97069de)
我目前并未对您的其余代码进行修改，只将conf目录下的spk_onl_tfm_enc_dec_nonautoreg.yaml中的train_data_dir和val_data_dir修改成了我的数据集中的训练集和验证集的路径。
尝试开始训练后卡在这一步：
![image](https://github.com/user-attachments/assets/000c0601-afe8-462d-9b58-ddecba9efeee)
便报错：
Sanity Checking: 0it [00:00, ?it/s]Traceback (most recent call last):                                                                                                                       
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/trainer/call.py", line 36, in _call_and_handle_interrupt                                              
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)                                                                                                   
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 90, in launch                                        
    return function(*args, **kwargs)                                                                                                                                                        
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 624, in _fit_impl                                                           
    self._run(model, ckpt_path=self.ckpt_path)                                                                                                                                              
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1061, in _run                                                               
    results = self._run_stage()                                                                                                                                                             
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1140, in _run_stage                                                         
    self._run_train()                                                                                                                                                                       
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1153, in _run_train                                                         
    self._run_sanity_check()                                                                                                                                                                
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/trainer/trainer.py", line 1225, in _run_sanity_check                               
  val_loop.run()
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 152, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/loops/loop.py", line 199, in run
    self.advance(*args, **kwargs)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 121, in advance
    batch = next(data_fetcher)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 184, in __next__
    return self.fetching_function()
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 265, in fetching_function
    self._fetch_next_batch(self.dataloader_iter)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/pytorch_lightning/utilities/fetching.py", line 280, in _fetch_next_batch
    batch = next(iterator)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 628, in __next__
    data = self._next_data()
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1333, in _next_data
   return self._process_data(data)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1359, in _process_data
    data.reraise()
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/lz/anaconda3/envs/FS-EEND/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/data/lz/FS-EEND/datasets/diarization_dataset.py", line 92, in __getitem__
    Y = transform(Y, self.input_transform)
  File "/home/data/lz/FS-EEND/datasets/feature.py", line 57, in transform
    Y = np.dot(Y ** 2, mel_basis.T)
  File "<__array_function__ internals>", line 180, in dot
ValueError: shapes (0,129,400000) and (129,23) not aligned: 400000 (dim 2) != 129 (dim 0)

我想数据集方面经过几轮核实后应该没有结构上的问题，我想知道这是哪方面出了差错。
我深知这是一个低级问题，我在第一步就失败了却也无力解决，但也希望得到老师的指导。
再次感谢！

**Comment by 2120171255** [comment]
你好，我也遇到了类似问题，请教下如何把wav音频文件转为单通道文件，我的邮箱是1030567459@qq.com，期待您的回复，感谢
